version: '3.9'
name: database-mysql

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khang412
    ports: 
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  mysql_data: